name: Atualizar CDI

on:
  schedule:
    - cron: '0 10 * * *'  # Todos os dias às 07:00 (horário de Brasília)
  workflow_dispatch:      # Permite rodar manualmente também

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar dependências Python
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Rodar o script scrape_cdi.py
        run: python scrape_cdi.py

      - name: Commitar arquivo cdi.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/cdi.json
          git commit -m "Atualizar CDI automaticamente" || echo "Nenhuma mudança"
          git push
