name: Atualizar IPCA 12M

on:
  schedule:
    - cron: '0 3 * * *'  # Executa diariamente às 03:00 UTC
  workflow_dispatch:  # Permite execução manual

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: pip install requests beautifulsoup4

      - name: Executar scraper do IPCA
        run: python scrape_ipca.py

      - name: Commitar resultado
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ipca12m.json
          git commit -m "Atualização diária do IPCA acumulado (12 meses)"
          git push
