name: Atualizar IPCA

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install requests beautifulsoup4

      - name: Executar script de scraping do IPCA
        run: python scrape_ipca.py

      - name: Commit e push do IPCA
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ipca12m.json
          git commit -m "Atualização diária do IPCA acumulado (12 meses)"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
